import type {
  PlannedWorkout,
  WorkoutBlock,
  WorkoutResult,
  WorkspaceState,
} from "../domain/types";
import { deepFreeze } from "../domain/immutable";

const easyBlock = (distanceKm: number): WorkoutBlock[] => [
  { kind: "easy", distanceKm },
];

const plannedWorkout = (
  id: string,
  date: PlannedWorkout["date"],
  type: PlannedWorkout["type"],
  title: string,
  purpose: string,
  distanceKm: number,
  blocks: WorkoutBlock[] = easyBlock(distanceKm),
): PlannedWorkout => ({
  id,
  date,
  type,
  title,
  purpose,
  distanceKm,
  prescription: { blocks },
});

const completedResult = (
  date: string,
  plannedWorkoutId: string,
  distanceKm: number,
): WorkoutResult => ({
  id: `result-${date}`,
  plannedWorkoutId,
  startedAt: `${date}T07:00:00+01:00`,
  status: "completed",
  summary: { distanceKm },
  laps: [],
});

export const DEMO_WORKSPACE_STATE = {
  seedVersion: "demo-athlete-v1",
  clock: {
    now: "2026-08-26T20:15:00+01:00",
    timeZone: "Europe/London",
  },
  athlete: {
    id: "athlete-sam",
    displayName: "Sam",
    normalWeeklyVolumeKm: { min: 42, max: 48 },
    recentHalfMarathonSeconds: 6_120,
    thresholdPaceSecondsPerKm: 278,
  },
  targetRace: {
    id: "race-brighton-marathon-2027",
    name: "Brighton Marathon",
    date: "2027-04-04",
    distanceKm: 42.195,
    objectiveSeconds: 13_200,
  },
  trainingPhase: {
    id: "phase-aerobic-development",
    name: "Aerobic development",
  },
  observations: {
    adapter: "synthetic-coros-shaped",
    asOf: "2026-08-26T20:15:00+01:00",
    provenance:
      "Seeded internal adapter grounded in documented read-only COROS capability classes; not an authenticated COROS wire format.",
    trainingLoad: { shortTerm: 68, longTerm: 51, ratio: 1.33 },
    recovery: { percent: 46, classification: "partially_recovered" },
    sleep: { durationMinutes: 442, score: 81 },
    sleepHrvMs: { value: 55, syntheticNormalRange: [49, 63] },
    restingHeartRateBpm: 52,
    dailyStress: "unremarkable",
  },
  trainingPlan: {
    planVersion: 1,
    plannedWorkouts: [
      plannedWorkout(
        "planned-2026-08-02-long",
        "2026-08-02",
        "long_run",
        "14 km long run",
        "Build durable aerobic time",
        14,
      ),
      plannedWorkout(
        "planned-2026-08-04-easy",
        "2026-08-04",
        "easy",
        "8 km easy",
        "Comfortable aerobic running",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-06-threshold",
        "2026-08-06",
        "threshold",
        "Threshold intervals",
        "Develop sustainable speed",
        11,
      ),
      plannedWorkout(
        "planned-2026-08-08-recovery",
        "2026-08-08",
        "recovery",
        "6 km recovery",
        "Absorb the week's training",
        6,
      ),
      plannedWorkout(
        "planned-2026-08-09-long",
        "2026-08-09",
        "long_run",
        "16 km long run",
        "Extend aerobic endurance",
        16,
      ),
      plannedWorkout(
        "planned-2026-08-11-easy",
        "2026-08-11",
        "easy",
        "8 km easy",
        "Maintain aerobic frequency",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-13-easy",
        "2026-08-13",
        "easy",
        "8 km easy",
        "Comfortable aerobic running",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-15-strides",
        "2026-08-15",
        "easy",
        "8 km easy with strides",
        "Keep relaxed leg speed",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-16-long",
        "2026-08-16",
        "long_run",
        "18 km long run",
        "Build aerobic durability",
        18,
      ),
      plannedWorkout(
        "planned-2026-08-18-easy",
        "2026-08-18",
        "easy",
        "10 km easy",
        "Maintain aerobic volume",
        10,
      ),
      plannedWorkout(
        "planned-2026-08-19-steady",
        "2026-08-19",
        "steady",
        "12 km steady with 5 km tempo",
        "Build controlled aerobic strength",
        12,
      ),
      plannedWorkout(
        "planned-2026-08-21-easy",
        "2026-08-21",
        "easy",
        "8 km easy",
        "Recover between longer sessions",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-22-recovery",
        "2026-08-22",
        "recovery",
        "6 km recovery",
        "Prepare for the long run",
        6,
      ),
      plannedWorkout(
        "planned-2026-08-23-long",
        "2026-08-23",
        "long_run",
        "20 km long run",
        "Extend aerobic endurance",
        20,
      ),
      plannedWorkout(
        "planned-2026-08-24-recovery",
        "2026-08-24",
        "recovery",
        "6 km recovery",
        "Recover from the long run",
        6,
      ),
      plannedWorkout(
        "planned-2026-08-26-threshold",
        "2026-08-26",
        "threshold",
        "5 × 1 km threshold",
        "Develop threshold pace under control",
        13,
        [
          { kind: "warmup", distanceKm: 2 },
          {
            kind: "repeat",
            repetitions: 5,
            workDistanceKm: 1,
            targetPaceSecondsPerKm: { min: 275, max: 280 },
            recoverySeconds: 90,
          },
          { kind: "cooldown", distanceKm: 1.5 },
        ],
      ),
      plannedWorkout(
        "planned-2026-08-27-recovery",
        "2026-08-27",
        "recovery",
        "6 km recovery",
        "Restore easy movement after threshold work",
        6,
      ),
      plannedWorkout(
        "planned-2026-08-29-strides",
        "2026-08-29",
        "easy",
        "8 km easy with strides",
        "Keep relaxed leg speed",
        8,
      ),
      plannedWorkout(
        "planned-2026-08-30-long",
        "2026-08-30",
        "long_run",
        "18 km long run",
        "Build aerobic durability",
        18,
      ),
    ],
  },
  workoutResults: [
    completedResult("2026-08-13", "planned-2026-08-13-easy", 8),
    completedResult("2026-08-15", "planned-2026-08-15-strides", 8),
    completedResult("2026-08-16", "planned-2026-08-16-long", 18),
    completedResult("2026-08-18", "planned-2026-08-18-easy", 10),
    completedResult("2026-08-19", "planned-2026-08-19-steady", 12),
    completedResult("2026-08-21", "planned-2026-08-21-easy", 8),
    completedResult("2026-08-22", "planned-2026-08-22-recovery", 6),
    completedResult("2026-08-23", "planned-2026-08-23-long", 20),
    completedResult("2026-08-24", "planned-2026-08-24-recovery", 6),
    {
      id: "result-2026-08-26-threshold",
      plannedWorkoutId: "planned-2026-08-26-threshold",
      startedAt: "2026-08-26T17:30:00+01:00",
      status: "partial",
      summary: {
        distanceKm: 7.5,
        completedWorkRepetitions: 3,
        plannedWorkRepetitions: 5,
      },
      laps: [
        { id: "lap-threshold-warmup", kind: "warmup", distanceKm: 2 },
        {
          id: "lap-threshold-rep-1",
          kind: "work",
          distanceKm: 1,
          paceSecondsPerKm: 276,
          averageHeartRateBpm: 165,
        },
        {
          id: "lap-threshold-rep-2",
          kind: "work",
          distanceKm: 1,
          paceSecondsPerKm: 279,
          averageHeartRateBpm: 171,
        },
        {
          id: "lap-threshold-rep-3",
          kind: "work",
          distanceKm: 1,
          paceSecondsPerKm: 288,
          averageHeartRateBpm: 176,
        },
        { id: "lap-threshold-cooldown", kind: "cooldown", distanceKm: 1 },
      ],
    },
  ],
  athleteFeedback: [],
  processedRequestIds: [],
  appliedReviewIds: [],
  adaptationReceipts: [],
  mutationHistory: [],
} satisfies WorkspaceState;

export function createDemoWorkspaceState(): WorkspaceState {
  return deepFreeze(structuredClone(DEMO_WORKSPACE_STATE));
}
